# Uncomment the next line to define a global platform for your project
platform :ios, '15.2'

target 'TourMate' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for TourMate
  # Add the Firebase pod for Google Analytics
  # For Analytics without IDFA collection capability, use this pod instead
  # pod ‘Firebase/AnalyticsWithoutAdIdSupport’
  pod 'Firebase/Analytics'
  
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
  
  target 'TourMateTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  target 'TourMateUITests' do
    # Pods for testing
  end
  
end
