# Uncomment the next line to define a global platform for your project
platform :ios, '15.2'

target 'TourMate' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for TourMate
  # Add the Firebase pod for Google Analytics
  # For Analytics without IDFA collection capability, use this pod instead
  # pod ‘Firebase/AnalyticsWithoutAdIdSupport’
  pod 'Firebase/Analytics'
  
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
  pod 'GoogleSignIn'
  
  target 'TourMateTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  target 'TourMateUITests' do
    # Pods for testing
  end
  
  post_install do |installer|
    # Speed up Xcode Build
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        if config.name == 'Debug'
          config.build_settings['OTHER_SWIFT_FLAGS'] = ['$(inherited)', '-Onone']
          config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Owholemodule'
        end
      end
    end
    # Fix build failing for M1 Mac
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
  
end
