@startuml

hide footbox

create PlanView

create PlanDiffView
PlanView -> PlanDiffView: PlanDiffView(planVM, commentsVM, upvotesVM)

create PlanViewModel
PlanDiffView -> PlanViewModel: Creates copies of PlanVM

PlanDiffView -> PlanViewModel: leftViewModel.diffPlan(rightViewModel)

PlanViewModel --> PlanDiffView: PlanDiffMap

create PlanDiffTextView
PlanDiffView -> PlanDiffTextView: PlanDiffTextView(PlanDiffMap)

create SimplePlanView
PlanDiffView -> SimplePlanView: SimplePlanView(copiedPlanVM, copiedCommentsVM, copiedUpvotesVM)

SimplePlanView -> PlanViewModel: Attach Delegates

create VersionPickerView
SimplePlanView -> VersionPickerView: Binds planVersion

loop
VersionPickerView -> SimplePlanView: onChange(newVersion)

SimplePlanView -> PlanViewModel: setVersionNumber(newVersion)

PlanViewModel -> PlanViewModel: update(planWithVersionNumber)

PlanViewModel -> PlanViewModel: self.plan = plan

PlanViewModel -> PlanViewModel: updateDelegates()

PlanViewModel -> SimplePlanView : @Published

PlanViewModel -> PlanDiffTextView : @Published

end loop

deactivate PlanView
@enduml
